[features]
seeds = true

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "https://billowing-purple-haze.solana-devnet.quiknode.pro/ea3ee1962c14f0c07f1524930fd6bc014290b601/"
wallet = "/home/scott/.config/solana/id.json"

[programs.localnet]
bubblegum="BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY"
token_metadata="7ioTaHbALyMreTcp6PwK32Gru6o8zi5J4MGxSwKEBN8Y"

[programs.devnet]
token_metadata="META4s4fSmpkTbZoUsgC1oBnWB31vQcmnN8giPw51Zu"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "target/deploy/mpl_token_metadata.so"

[[test.genesis]]
address = "hausS13jsjafwWwGqZTUQRmWyvyxn9EQpqMwV1PBBmk"
program = "target/deploy/mpl_auction_house.so"

[[test.genesis]]
address = "qntmGodpGkrM42mN68VCZHXnKqDCT8rdY23wFcXCLPd"
program = "target/deploy/mpl_token_entangler.so"

[[test.genesis]]
address = "SaLeTjyUa5wXHnGuewUSyJ5JWZaHwz3TxqUntCE9czo"
program = "target/deploy/mpl_fixed_price_sale.so"

[[test.genesis]]
address = "gdrpGjVffourzkdDRrQmySw4aTHr8a3xmQzzxSwFD1a"
program = "target/deploy/mpl_gumdrop.so"

[[test.genesis]]
address = "hyDQ4Nz1eYyegS6JfenyKwKzYxRsCWCriYSAjtzP4Vg"
program = "target/deploy/mpl_hydra.so"

[workspace]
members = [
  "token-metadata/program",
  "bubblegum/program",
]
